#############################################################################
# Makefile for building: build/DONTFLOAT
# Generated by qmake (3.1) (Qt 6.4.2)
# Project:  DONTFLOAT.pro
# Template: app
# Command: /usr/lib/qt6/bin/qmake6 -o Makefile DONTFLOAT.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -fPIC -O2 -std=gnu++1z -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -Iinclude -Ibuild/ui -Ibuild/moc -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -Ibuild/moc -Ibuild/ui -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++
QMAKE         = /usr/lib/qt6/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt6/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt6/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = DONTFLOAT1.0.0
DISTDIR = /home/ili4yov-ika/Локальные\ репозитории/DONTFLOAT/build/obj/DONTFLOAT1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt6Multimedia.so /usr/lib/x86_64-linux-gnu/libQt6Widgets.so /usr/lib/x86_64-linux-gnu/libQt6Gui.so /usr/lib/x86_64-linux-gnu/libGLX.so /usr/lib/x86_64-linux-gnu/libOpenGL.so /usr/lib/x86_64-linux-gnu/libQt6Network.so /usr/lib/x86_64-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/waveformview.cpp \
		src/pitchgridwidget.cpp \
		src/waveformcolors.cpp \
		src/bpmanalyzer.cpp \
		src/keyanalyzer.cpp \
		src/waveformanalyzer.cpp \
		src/audiocommand.cpp \
		src/loadfiledialog.cpp \
		src/metronomesettingsdialog.cpp \
		src/metronomecontroller.cpp \
		src/beatfixcommand.cpp \
		src/timestretchcommand.cpp \
		src/timestretchprocessor.cpp build/rcc/qrc_resources.cpp \
		build/moc/moc_mainwindow.cpp \
		build/moc/moc_waveformview.cpp \
		build/moc/moc_pitchgridwidget.cpp \
		build/moc/moc_loadfiledialog.cpp \
		build/moc/moc_metronomesettingsdialog.cpp \
		build/moc/moc_metronomecontroller.cpp
OBJECTS       = build/obj/src/main.o \
		build/obj/src/mainwindow.o \
		build/obj/src/waveformview.o \
		build/obj/src/pitchgridwidget.o \
		build/obj/src/waveformcolors.o \
		build/obj/src/bpmanalyzer.o \
		build/obj/src/keyanalyzer.o \
		build/obj/src/waveformanalyzer.o \
		build/obj/src/audiocommand.o \
		build/obj/src/loadfiledialog.o \
		build/obj/src/metronomesettingsdialog.o \
		build/obj/src/metronomecontroller.o \
		build/obj/src/beatfixcommand.o \
		build/obj/src/timestretchcommand.o \
		build/obj/src/timestretchprocessor.o \
		build/obj/build/rcc/qrc_resources.o \
		build/obj/build/moc/moc_mainwindow.o \
		build/obj/build/moc/moc_waveformview.o \
		build/obj/build/moc/moc_pitchgridwidget.o \
		build/obj/build/moc/moc_loadfiledialog.o \
		build/obj/build/moc/moc_metronomesettingsdialog.o \
		build/obj/build/moc/moc_metronomecontroller.o
DIST          = /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		DONTFLOAT.pro include/mainwindow.h \
		include/waveformview.h \
		include/pitchgridwidget.h \
		include/waveformcolors.h \
		include/bpmanalyzer.h \
		include/keyanalyzer.h \
		include/waveformanalyzer.h \
		include/audiocommand.h \
		include/loadfiledialog.h \
		include/metronomesettingsdialog.h \
		include/metronomecontroller.h \
		include/beatfixcommand.h \
		include/timestretchcommand.h \
		include/timestretchprocessor.h src/main.cpp \
		src/mainwindow.cpp \
		src/waveformview.cpp \
		src/pitchgridwidget.cpp \
		src/waveformcolors.cpp \
		src/bpmanalyzer.cpp \
		src/keyanalyzer.cpp \
		src/waveformanalyzer.cpp \
		src/audiocommand.cpp \
		src/loadfiledialog.cpp \
		src/metronomesettingsdialog.cpp \
		src/metronomecontroller.cpp \
		src/beatfixcommand.cpp \
		src/timestretchcommand.cpp \
		src/timestretchprocessor.cpp
QMAKE_TARGET  = DONTFLOAT
DESTDIR       = build/
TARGET        = build/DONTFLOAT


first: all
####### Build rules

build/DONTFLOAT: build/ui/ui_mainwindow.h build/ui/ui_loadfiledialog.h build/ui/ui_metronomesettingsdialog.h $(OBJECTS)  
	@test -d build/ || mkdir -p build/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DONTFLOAT.pro /usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		DONTFLOAT.pro \
		resources.qrc \
		/usr/lib/x86_64-linux-gnu/libQt6Multimedia.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Core.prl
	$(QMAKE) -o Makefile DONTFLOAT.pro -spec linux-g++
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf:
DONTFLOAT.pro:
resources.qrc:
/usr/lib/x86_64-linux-gnu/libQt6Multimedia.prl:
/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt6Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt6Network.prl:
/usr/lib/x86_64-linux-gnu/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile DONTFLOAT.pro -spec linux-g++

qmake_all: FORCE


all: Makefile build/DONTFLOAT

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/mainwindow.h include/waveformview.h include/pitchgridwidget.h include/waveformcolors.h include/bpmanalyzer.h include/keyanalyzer.h include/waveformanalyzer.h include/audiocommand.h include/loadfiledialog.h include/metronomesettingsdialog.h include/metronomecontroller.h include/beatfixcommand.h include/timestretchcommand.h include/timestretchprocessor.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/waveformview.cpp src/pitchgridwidget.cpp src/waveformcolors.cpp src/bpmanalyzer.cpp src/keyanalyzer.cpp src/waveformanalyzer.cpp src/audiocommand.cpp src/loadfiledialog.cpp src/metronomesettingsdialog.cpp src/metronomecontroller.cpp src/beatfixcommand.cpp src/timestretchcommand.cpp src/timestretchprocessor.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.ui ui/loadfiledialog.ui ui/metronomesettingsdialog.ui $(DISTDIR)/
	$(COPY_FILE) --parents translations/DONTFLOAT_ru_RU.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: build/rcc/qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/rcc/qrc_resources.cpp
build/rcc/qrc_resources.cpp: resources.qrc \
		/usr/lib/qt6/libexec/rcc
	/usr/lib/qt6/libexec/rcc -name resources resources.qrc -o build/rcc/qrc_resources.cpp

compiler_moc_predefs_make_all: build/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc/moc_predefs.h
build/moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -fPIC -O2 -std=gnu++1z -Wall -Wextra -fPIC -dM -E -o build/moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc/moc_mainwindow.cpp build/moc/moc_waveformview.cpp build/moc/moc_pitchgridwidget.cpp build/moc/moc_loadfiledialog.cpp build/moc/moc_metronomesettingsdialog.cpp build/moc/moc_metronomecontroller.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_mainwindow.cpp build/moc/moc_waveformview.cpp build/moc/moc_pitchgridwidget.cpp build/moc/moc_loadfiledialog.cpp build/moc/moc_metronomesettingsdialog.cpp build/moc/moc_metronomecontroller.cpp
build/moc/moc_mainwindow.cpp: include/mainwindow.h \
		include/waveformview.h \
		include/bpmanalyzer.h \
		include/waveformcolors.h \
		include/pitchgridwidget.h \
		include/metronomecontroller.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/include' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/ui' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/moc' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/mainwindow.h -o build/moc/moc_mainwindow.cpp

build/moc/moc_waveformview.cpp: include/waveformview.h \
		include/bpmanalyzer.h \
		include/waveformcolors.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/include' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/ui' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/moc' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/waveformview.h -o build/moc/moc_waveformview.cpp

build/moc/moc_pitchgridwidget.cpp: include/pitchgridwidget.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/include' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/ui' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/moc' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/pitchgridwidget.h -o build/moc/moc_pitchgridwidget.cpp

build/moc/moc_loadfiledialog.cpp: include/loadfiledialog.h \
		include/bpmanalyzer.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/include' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/ui' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/moc' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/loadfiledialog.h -o build/moc/moc_loadfiledialog.cpp

build/moc/moc_metronomesettingsdialog.cpp: include/metronomesettingsdialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/include' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/ui' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/moc' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/metronomesettingsdialog.h -o build/moc/moc_metronomesettingsdialog.cpp

build/moc/moc_metronomecontroller.cpp: include/metronomecontroller.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/include' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/ui' -I'/home/ili4yov-ika/Локальные репозитории/DONTFLOAT/build/moc' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/metronomecontroller.h -o build/moc/moc_metronomecontroller.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui/ui_mainwindow.h build/ui/ui_loadfiledialog.h build/ui/ui_metronomesettingsdialog.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui/ui_mainwindow.h build/ui/ui_loadfiledialog.h build/ui/ui_metronomesettingsdialog.h
build/ui/ui_mainwindow.h: ui/mainwindow.ui \
		/usr/lib/qt6/libexec/uic
	/usr/lib/qt6/libexec/uic ui/mainwindow.ui -o build/ui/ui_mainwindow.h

build/ui/ui_loadfiledialog.h: ui/loadfiledialog.ui \
		/usr/lib/qt6/libexec/uic
	/usr/lib/qt6/libexec/uic ui/loadfiledialog.ui -o build/ui/ui_loadfiledialog.h

build/ui/ui_metronomesettingsdialog.h: ui/metronomesettingsdialog.ui \
		/usr/lib/qt6/libexec/uic
	/usr/lib/qt6/libexec/uic ui/metronomesettingsdialog.ui -o build/ui/ui_metronomesettingsdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/obj/src/main.o: src/main.cpp include/mainwindow.h \
		include/waveformview.h \
		include/bpmanalyzer.h \
		include/waveformcolors.h \
		include/pitchgridwidget.h \
		include/metronomecontroller.h \
		include/waveformanalyzer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/src/main.o src/main.cpp

build/obj/src/mainwindow.o: src/mainwindow.cpp include/mainwindow.h \
		include/waveformview.h \
		include/bpmanalyzer.h \
		include/waveformcolors.h \
		include/pitchgridwidget.h \
		include/metronomecontroller.h \
		include/beatfixcommand.h \
		include/timestretchcommand.h \
		build/ui/ui_mainwindow.h \
		include/loadfiledialog.h \
		include/metronomesettingsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/src/mainwindow.o src/mainwindow.cpp

build/obj/src/waveformview.o: src/waveformview.cpp include/waveformview.h \
		include/bpmanalyzer.h \
		include/waveformcolors.h \
		include/timestretchprocessor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/src/waveformview.o src/waveformview.cpp

build/obj/src/pitchgridwidget.o: src/pitchgridwidget.cpp include/pitchgridwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/src/pitchgridwidget.o src/pitchgridwidget.cpp

build/obj/src/waveformcolors.o: src/waveformcolors.cpp include/waveformcolors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/src/waveformcolors.o src/waveformcolors.cpp

build/obj/src/bpmanalyzer.o: src/bpmanalyzer.cpp include/bpmanalyzer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/src/bpmanalyzer.o src/bpmanalyzer.cpp

build/obj/src/keyanalyzer.o: src/keyanalyzer.cpp include/keyanalyzer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/src/keyanalyzer.o src/keyanalyzer.cpp

build/obj/src/waveformanalyzer.o: src/waveformanalyzer.cpp include/waveformanalyzer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/src/waveformanalyzer.o src/waveformanalyzer.cpp

build/obj/src/audiocommand.o: src/audiocommand.cpp include/audiocommand.h \
		include/waveformview.h \
		include/bpmanalyzer.h \
		include/waveformcolors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/src/audiocommand.o src/audiocommand.cpp

build/obj/src/loadfiledialog.o: src/loadfiledialog.cpp include/loadfiledialog.h \
		include/bpmanalyzer.h \
		build/ui/ui_loadfiledialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/src/loadfiledialog.o src/loadfiledialog.cpp

build/obj/src/metronomesettingsdialog.o: src/metronomesettingsdialog.cpp include/metronomesettingsdialog.h \
		include/metronomecontroller.h \
		build/ui/ui_metronomesettingsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/src/metronomesettingsdialog.o src/metronomesettingsdialog.cpp

build/obj/src/metronomecontroller.o: src/metronomecontroller.cpp include/metronomecontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/src/metronomecontroller.o src/metronomecontroller.cpp

build/obj/src/beatfixcommand.o: src/beatfixcommand.cpp include/beatfixcommand.h \
		include/waveformview.h \
		include/bpmanalyzer.h \
		include/waveformcolors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/src/beatfixcommand.o src/beatfixcommand.cpp

build/obj/src/timestretchcommand.o: src/timestretchcommand.cpp include/timestretchcommand.h \
		include/waveformview.h \
		include/bpmanalyzer.h \
		include/waveformcolors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/src/timestretchcommand.o src/timestretchcommand.cpp

build/obj/src/timestretchprocessor.o: src/timestretchprocessor.cpp include/timestretchprocessor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/src/timestretchprocessor.o src/timestretchprocessor.cpp

build/obj/build/rcc/qrc_resources.o: build/rcc/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/build/rcc/qrc_resources.o build/rcc/qrc_resources.cpp

build/obj/build/moc/moc_mainwindow.o: build/moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/build/moc/moc_mainwindow.o build/moc/moc_mainwindow.cpp

build/obj/build/moc/moc_waveformview.o: build/moc/moc_waveformview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/build/moc/moc_waveformview.o build/moc/moc_waveformview.cpp

build/obj/build/moc/moc_pitchgridwidget.o: build/moc/moc_pitchgridwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/build/moc/moc_pitchgridwidget.o build/moc/moc_pitchgridwidget.cpp

build/obj/build/moc/moc_loadfiledialog.o: build/moc/moc_loadfiledialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/build/moc/moc_loadfiledialog.o build/moc/moc_loadfiledialog.cpp

build/obj/build/moc/moc_metronomesettingsdialog.o: build/moc/moc_metronomesettingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/build/moc/moc_metronomesettingsdialog.o build/moc/moc_metronomesettingsdialog.cpp

build/obj/build/moc/moc_metronomecontroller.o: build/moc/moc_metronomecontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/build/moc/moc_metronomecontroller.o build/moc/moc_metronomecontroller.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/DONTFLOAT/bin || mkdir -p $(INSTALL_ROOT)/opt/DONTFLOAT/bin
	$(QINSTALL_PROGRAM) build/$(QMAKE_TARGET) $(INSTALL_ROOT)/opt/DONTFLOAT/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/DONTFLOAT/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/DONTFLOAT/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/DONTFLOAT/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

